### ISSUE TITLE
오타 제보드려요:)

### ISSUE THREAD

**Issue by 00parkjihye** [ksy90101/TIL#2]
<img width="699" alt="Stack vs Queue 오타 샇-쌓" src="https://user-images.githubusercontent.com/75290488/104871596-d3e28d00-598e-11eb-9b72-c2f361590fb4.png">
우연히 들어와 정독하던 중에 별거 아니지만 작은 오타가 있어서 제보드려요 :)
'샇'이게 된다 > '쌓'이게 된다

**Comment by ksy90101** [comment]
감사합니다 :)
